// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPp1WH1x2Xjffe4WuB0Jxca-hWWqC8Ijw',
    appId: '1:241817045331:web:b35ef73ccdd77e0e9d39a6',
    messagingSenderId: '241817045331',
    projectId: 'intrazero-b912c',
    authDomain: 'intrazero-b912c.firebaseapp.com',
    storageBucket: 'intrazero-b912c.appspot.com',
    measurementId: 'G-5RW3TR0Z8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvzBGXQMXHsuYCozCqdGYfGAeCiIgymo',
    appId: '1:241817045331:android:bade51bae8606b1a9d39a6',
    messagingSenderId: '241817045331',
    projectId: 'intrazero-b912c',
    storageBucket: 'intrazero-b912c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqVs2oRdHzWob-ibRUOYIqTa_9wCQfy0w',
    appId: '1:241817045331:ios:e0e1a85277d2708f9d39a6',
    messagingSenderId: '241817045331',
    projectId: 'intrazero-b912c',
    storageBucket: 'intrazero-b912c.appspot.com',
    iosBundleId: 'com.example.intrazero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqVs2oRdHzWob-ibRUOYIqTa_9wCQfy0w',
    appId: '1:241817045331:ios:e0e1a85277d2708f9d39a6',
    messagingSenderId: '241817045331',
    projectId: 'intrazero-b912c',
    storageBucket: 'intrazero-b912c.appspot.com',
    iosBundleId: 'com.example.intrazero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPp1WH1x2Xjffe4WuB0Jxca-hWWqC8Ijw',
    appId: '1:241817045331:web:37bed906fd044d339d39a6',
    messagingSenderId: '241817045331',
    projectId: 'intrazero-b912c',
    authDomain: 'intrazero-b912c.firebaseapp.com',
    storageBucket: 'intrazero-b912c.appspot.com',
    measurementId: 'G-XQRCY911JZ',
  );
}
